version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend/run.py:/run.py"
      - "./backend/app:/app"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend/src:/usr/src/app/src"

  app:
    image: nginx:latest
    ports:
      - "4200:80"
    volumes:
      - "./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx-config/conf.d:/etc/nginx/conf.d:ro"
    depends_on:
      - backend
      - frontend

  database:
    image: mongo
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
